# Generated by Django 4.2.2 on 2023-06-25 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('create_date', models.DateField(auto_now=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('short_description', models.CharField(max_length=300)),
                ('main_description', models.TextField()),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'db_table': 'Article',
            },
        ),
    ]
