# Generated by Django 4.2.2 on 2023-06-26 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_article_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default='no title', max_length=200),
            preserve_default=False,
        ),
    ]
